version: '3.1'
services:
  ejemplosecret:
    container_name: ejemplo_secret
    image: nginxdemos/hello
    secrets:                    
     - secret_file

secrets:                       
  secret_file:
    file: mi_secret_en_fichero.txt
